- hosts: all
  vars:
    user: hcvst
    config_repo: https://bitbucket.org/hc/ubuntuconfig
    config_dir: config.git
  tasks:
  - name: install ubuntu packages
    sudo: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - i3
      - zsh
      - autojump
  - name: Set zsh as default shell
    sudo: yes
    user: name={{ user }} shell=/bin/zsh 
  - name: Clone my configuration (dotfiles, ...)
    shell: git clone --no-checkout {{ config_repo }} {{ config_dir }} 
    args:
      chdir: /home/{{ user }} 
      creates: /home/{{ user }}/{{ config_dir }} 
  - name: Configure my configuration repo 
    shell: git config core.worktree "../../" chdir=/home/{{ user }}/{{ config_dir }}
  - name: Fetchq my configuration files 
    shell: git reset --hard origin/master chdir=/home/{{ user }}/{{ config_dir }}
