- hosts: all
  tasks:
  - name: install ubuntu packages
    sudo: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - i3
      - zsh
  - name: Set zsh as default shell
    sudo: yes
    user: name=$user shell=/bin/zsh 
